require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.3

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
